
version: "3"
services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  server:
    build:
      context: .
      dockerfile: BackEnd.Dockerfile
    container_name: server
    depends_on:
      - "db"
    ports:
      - "8080:8080"
    command: bash -c "/usr/wait-for-it.sh --timeout=0 mysql:3306 && sudo java -DMYSQL_HOST=mysql -DMYSQL_USER_NAME=root -DMYSQL_USER_PASSWORD=password -jar /srv/uploading-files-0.0.1-SNAPSHOT.jar"

  front-end:
    build:
      context: .
      dockerfile: FrontEnd.Dockerfile
    depends_on:
      - server
    ports:
      - "3000:3000"
    command: npm start


